server:
  port: 8101

spring:
  application:
    name: rabbit-provider

  rabbitmq:
    host: 116.85.15.180
    port: 5672
    username: admin
    password: admin

    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已经发送到队列中 当消息匹配到Queue并且失败时，会通过回调returnedMessage()方法返回消息
    publisher-returns: true
    # 设置为true时。指定消息在没有被队列接收时会通过回调returnedMessage()方法退回。
    template:
      mandatory: true