server:
  port: 8201

spring:
  application:
    name: rabbit-consumer

  rabbitmq:
    host: 116.85.15.180
    port: 5672
    username: admin
    password: admin

    listener:
      simple:
        acknowledge-mode: manual # 手动ack模式
        concurrency: 1 # 最少消费者数量
        max-concurrency: 10 # 最大消费者数量复